#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""resizR is a pyinotify PIL hack to resize images automatically

author: André Kelpe <efeshundertelf at googlemail dot com>
license: MIT
"""
from resizRmodules import resizRmain

if __name__ == "__main__":
    resizRmain.main()
